name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:
    inputs:
      buildFlags:
        required: false
        type: string
  workflow_dispatch:

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.6

      - name: Restore Previous Cache
        id: cache-build-windows-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
          key: cache-windows-build

      - name: Install Haxelib and Tools
        run: |
          mkdir C:\haxelib
          haxelib setup C:\haxelib
          haxelib install hxcpp > NUL
          haxelib install lime > NUL
          haxelib install openfl > NUL
          haxelib install actuate > NUL
          haxelib install format > NUL
          haxelib install hxp > NUL
          .\setup\windows.bat
        shell: cmd

      - name: Compile hxcpp manually
        run: |
          cd C:\haxelib\hxcpp\git\tools\run
          haxe compile.hxml
          cd ..\..\hxcpp
          haxe compile.hxml
        shell: cmd

      - name: Compile Project
        run: |
          haxelib run lime build windows -D ${{ inputs.buildFlags || 'commit' }}
        shell: cmd

      - name: Clear Previous Cache (Windows Build)
        uses: actions/github-script@v7
        with:
          script: |
            const caches = await github.rest.actions.getActionsCacheList({
              owner: context.repo.owner,
              repo: context.repo.repo,
            })
            for (const cache of caches.data.actions_caches || []) {
              if (cache.key === "cache-windows-build") {
                console.log(`Clearing ${cache.key}...`);
                await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                });
              }
            }

      - name: Save Current Cache
        uses: actions/cache/save@v4
        with:
          path: |
            .haxelib/
            export/release/windows/haxe/
            export/release/windows/obj/
          key: cache-windows-build

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windowsBuild
          path: export/release/windows/bin
